{
  "characterization": {
    "error": {
      "max_temperature_change": 3
    },
    "warning": {
      "all_files_analyzed": null,
      "all_sensors_scanned": null,
      "expected_runs_acquired": null
    }
  },
  "fileset": {
    "error": {
      "minimum_linreg_r": 0.9990
    },
    "warning": {
      "minimum_linreg_points": 20,
      "minimum_files_in_set": 3,
      "max_temperature_change": 2
    }
  },
  "sweepfile": {
    "error": {
      "minimum_saturated_points": 3,
    },
    "warning": {
      "minimum_linreg_r": 0.9990,
      "minimum_linreg_points": 7,
      "low_total_counts": 250,
    }
  }
}
